services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      cache_from:
        - client-cache
    image: client-cache
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.entrypoints=web
      - traefik.http.routers.client.rule=Host(`app.localhost`)
      - traefik.http.services.client.loadbalancer.server.port=3000
    networks:
      - web
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      cache_from:
        - server-cache
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: server-cache
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/target
    secrets:
      - github_api
    ports:
      - "8000:8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.rule=Host(`api.localhost`)
      - traefik.http.services.api.loadbalancer.server.port=8000
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/db?sslmode=disable
    networks:
      - web
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - web

volumes:
  database:
  tailscale-var-lib:

networks:
  web:
    name: web
    driver: bridge

secrets:
  github_api:
    file: /home/unixpariah/.config/sops-nix/secrets/github-api
