apiVersion: v1
kind: Namespace
metadata:
  name: portfolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-client
  namespace: portfolio
  labels:
    app: portfolio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-client
  template:
    metadata:
      labels:
        app: portfolio-client
    spec:
      containers:        
        - name: portfolio-client
          env:
            - name: HOST
              value: "0.0.0.0"
          image: ghcr.io/unixpariah/portfolio-client:prod
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-client
  namespace: portfolio
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: portfolio-client
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio
spec:
  ingressClassName: ingress-nginx
  rules:
    - host: portfolio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-client
                port:
                  number: 80
