apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: portfolio
data:
  init.sql: |
    CREATE TABLE projects (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        stars INTEGER NOT NULL,
        url TEXT NOT NULL,
        homepage TEXT
    );

    CREATE TABLE project_languages (
        project_id INTEGER NOT NULL,
        language TEXT NOT NULL,
        usage INTEGER NOT NULL,
        FOREIGN KEY (project_id) REFERENCES projects(id)
    );

    CREATE TABLE stats (
        id INTEGER PRIMARY KEY DEFAULT 1,
        name TEXT NOT NULL,
        bio TEXT,
        avatar_url TEXT NOT NULL,
        company TEXT,
        public_repos INTEGER NOT NULL,
        followers INTEGER NOT NULL,
        following INTEGER NOT NULL,
        location TEXT NOT NULL,
        hireable BOOLEAN NOT NULL
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
